### ISSUE TITLE
Typo in readme file

### ISSUE THREAD

**Issue by milo2012** [frohoff/jimmix#1]
Thank you for the awesome tool
There seems to be a typo for the "unregiste"r method.  The "unregister" method seems to be renamed as "unregisterMBean" in the source code.  

You might want to update the README file. Thanks

**Comment by frohoff** [comment]
Thanks, but this project is not mine and I just archived it to github from the [tar.gz file](http://www.synacktiv.com/ressources/jimmix-0.3.tar.gz) on the [synacktiv website](http://www.synacktiv.com/) for posterity (as noted by the project description). I have no plans to fork it or maintain it so any feedback should be directed to the original author(s).
